### PR TITLE
Google Drive driver

### PR DESCRIPTION
**Pull request by molobala**
I added Google Drive driver, need google-auth-library and to function use oauth2

### CODE REVIEW

**Comment by molobala** [comment]
I don't get what's wrong exactly , could you take a look at!

**Comment by RomainLanz** [comment]
Hey @molobala! 👋 

Sorry for the delay, I think Google Drive shouldn't be directly inside the core of the package.
You could create your own package and use the [`extend`](https://github.com/Slynova-Org/node-flydrive/wiki/Register-a-custom-driver) method to add it.

**Comment by molobala** [comment]
By what you mean, that is if I want to use google driver, in my project, but what if I want to add Google Drive support to the library! 
As you explained, create my own package, what about merging it with your package ?

**Comment by molobala** [comment]
I was gone on base of s3 driver

**Comment by RomainLanz** [comment]
I mean that if I merge your PR within the core of this package I'll need to maintain and test a huge code base that I didn't wrote myself + I don't believe a Google Drive driver should be in the core since it's a different type of provider.

What you could do instead is create your own repository with this code and create an node package. Then you can simply use the `extend` method of this package to add your driver.

```js
const Storage = require('@slynova/flydrive/Storage')
const StorageManager = require('@slynova/flydrive')
const GoogleDrive = require('flydrive-google-drive') // your package

const storage = new StorageManager(config)

storage.extend('myDriver', config => {
  return new Storage(
    new GoogleDrive(config)
  )
})
```

I hope it makes sens.

**Comment by molobala** [comment]
Done , you can check it please!
Git repo: https://github.com/molobala/flydrive-google-drive
Npm package: https://www.npmjs.com/package/flydrive-google-drive

**Comment by RomainLanz** [comment]
Seems cool !

I'll try it out and add it to the readme for people who want to use Google Drive 👌

**Comment by RomainLanz** [comment]
Closing since in the meanwhile since it's released as a standalone package. 😄

**Pull request closed without merging**
