### PR TITLE
Add list() method to S3 and Local drivers

### PR DESCRIPTION
**Pull request by thsteinmetz**
A `list(..)` method lets a user list all the objects/files in a bucket/directory.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Cool !

Could you add test for DigitalOcean Spaces driver too (since it uses S3 driver and should be compatible)?

**Comment by thsteinmetz** [comment]
@RomainLanz Ok. I created a Spaces account on Digital Ocean and updated to the test to verify it works exactly the same as AWS S3. All is good.

**Comment by thsteinmetz** [comment]
Looks like the build is failing due to no S3 and Spaces connection. I imagine this is expected.

**Comment by RomainLanz** [comment]
Yes, it's normal that test are failing.

I need to test this feature first before merging it and verify the format that all drivers return.
I want to have a consistent API across all driver.

**Comment by thsteinmetz** [comment]
@RomainLanz anything you need me to update?

**Comment by RomainLanz** [comment]
Not currently and unfortunately I haven't got the time to check the PR.

**Comment by thsteinmetz** [comment]
Closing PR.

**Pull request closed without merging**
