### PR TITLE
Update AwsS3 contructor to consume any S3 option

### PR DESCRIPTION
**Pull request by antwaanvh**

### CODE REVIEW

**Comment by antwaanvh** [comment]
@RomainLanz not sure why tests are failing, but could you check this out locally?

**Comment by RomainLanz** [comment]
Hey!

Yes for sure, I was completely busy this week. I'll take a look at this tomorrow.
Tests are failing because Travis doesn't use environment variable if I'm not the owner of the commit, this avoids security issue like people doing a `console.log` of all environments variables. 😄

**Comment by antwaanvh** [comment]
Ah that's perfect, thanks!

**Comment by RomainLanz** [comment]
Thanks! 😄 
Published as `0.1.6`

**Pull request merged**
